name: CI
"on":
  push:
    branches:
      - main
    paths:
      - src/**
  workflow_dispatch:
jobs:
  deploy_build:
    name: Build & deploy

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node 17
        uses: actions/setup-node@v1
        with:
          node-version: 17

      - name: Install yarn
        run: npm install --global yarn

      - name: Install dependencies
        run: yarn install

      - name: Setup ssh key
        run: set -eu && mkdir "$HOME/.ssh" && echo "${{ secrets.REMOTE_SSH_KEY }}" > "$HOME/.ssh/key" && chmod 600 "$HOME/.ssh/key"

      - name: Build
        run: yarn build

      - name: Deploy
        run: ssh -i ${{ secrets.REMOTE_SSH_KEY }} ubuntu@ec2-35-157-12-196.eu-central-1.compute.amazonaws.com
